### ISSUE TITLE
Get threaded tweets by font size

### ISSUE THREAD

**Issue by joe-mcbroom** [joe-mcbroom/tweetcreepr-api#11]

**Comment by joe-mcbroom** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [threaded tweet bug](https://trello.com/c/LXVu7bGN/7-threaded-tweet-bug)

**Comment by phil-willowtree** [comment]
is this bug solving for getting a clean tweet?
If its possible, we could select data-testid="tweet
![Screen Shot 2022-03-23 at 2 37 52 PM](https://user-images.githubusercontent.com/61247344/159772426-5ca842bc-a4ef-4d8c-8057-00f486e7ff26.png)
"
